### PR TITLE
Use for instead of if syntax to avoid compiler warnings

### PR DESCRIPTION
**Pull request by davidrohr**
Even though I liked the if / else syntax more since shorter, it produces compiler warnings in some cases, so I have changed to your for trick.

### CODE REVIEW

**Comment by rbx** [comment]
This will fix #30.

**Comment by rbx** [comment]
I wonder if the for loop doesn't break the constexpr-ness though. Feels like it shouldn't, but I'm not sure.

**Comment by davidrohr** [comment]
Depends on compiler optimization. In principle the compiler should be clever enough. But anyway, the if was also not an if constexpr (in fact it must not be, since there is no guarantuee that the log level provided by the user is constexpr).

**Comment by davidrohr** [comment]
Seems to be optimized away already at `-O1`: https://godbolt.org/z/h15rh4

**Review by rbx — APPROVED** [review]

**Pull request merged**
