### PR TITLE
Add 'alarm' and 'important' severities

### PR DESCRIPTION
**Pull request by rbx**
- Add two new severities:

~~fatal > error >  **alarm** > warn > state > **important** > info > debug > debug1 > debug2 > debug3 > debug4 > trace~~
EDIT: fatal > error >  **alarm** > **important** > warn > state > info > debug > debug1 > debug2 > debug3 > debug4 > trace

@davidrohr 

Also:
- Bump C++ requirement to 14.
- Deprecate uppercase severity names.

### CODE REVIEW

**Comment by davidrohr** [comment]
@rbx : thx, but I would need that important is higher than warning, i.e. ... error > alarm > important > warn > state ...

**Comment by rbx** [comment]
Now I'm confused. The one higher than 'warning' is 'alarm'. And from earlier discussion I remember that you used 'state' as 'important', so I added 'important' in that role.

**Comment by rbx** [comment]
Anyway, it is fine with me, just want to make sure it is indeed what you want.

**Comment by davidrohr** [comment]
> Anyway, it is fine with me, just want to make sure it is indeed what you want.

Using state as important didn't work well since there are globally quite some state messages.
And yes, I would indeed like important to be between alarm and warning.

**Comment by rbx** [comment]
Updated.

**Review by davidrohr — DISMISSED** [review]
thx, looks good. Please ping me when this is in a release.

**Comment by rbx** [comment]
@davidrohr this is now released with v1.10.0

**Pull request merged**
